fan_boost:
  description: Change fan speed for limited time
  fields:
    entity_id:
      description: Name of the entity.
      example: "fan.turkovcontroller"
    speed:
      description: "Boost speed. Available: off, low, medium, high"
      example: high
    duration:
      description: Duration in minutes
      example: 60
